name: "PHPUnit tests"

on:
  - push
  - pull_request

env:
  COMPOSER_FLAGS: "--ansi --no-interaction --no-progress --prefer-dist"

jobs:
  tests:
    name: "PHPUnit tests"

    runs-on: ubuntu-latest

    strategy:
      matrix:
        php-version:
          - "7.4"
        dependencies: [ highest ]

    steps:
      - name: "Checkout"
        uses: "actions/checkout@v2"

      - name: "Install PHP"
        uses: "shivammathur/setup-php@v2"
        with:
          coverage: "none"
          php-version: "${{ matrix.php-version }}"

      - name: "Install dependencies"
        run: |
          composer update ${{ env.COMPOSER_FLAGS }}

      - name: "Run tests"
        run: "composer exec phpunit -- --verbose"

      - name: Run test suite
        run: composer run-script unit-tests